# Generated by Django 4.0.2 on 2022-03-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='https://devsearch-testbucket.s3.amazonaws.com/user-default.png', null=True, upload_to='profiles/'),
        ),
    ]
