# Generated by Django 4.0.2 on 2022-03-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_options_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='https://devsearch-testbucket.s3.amazonaws.com/profiles/user-default.png', null=True, upload_to='profiles/'),
        ),
    ]
